
CREATE TABLE IF NOT EXISTS logs (uid STRING, sid INTEGER, name STRING, salary INTEGER)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
STORED AS TEXTFILE;

LOAD DATA INPATH '${hivevar:INPUT_PATH}' OVERWRITE INTO TABLE logs;
