jobs:

- hiveJob:
    queryFileUri: gs://wlt-demo-wf/sql/1_load-data-job.sql
    scriptVariables:
      INPUT_PATH: gs://wlt-demo-wf/dataset/records.tsv
  stepId: 1_load-data-job

- hiveJob:
    queryFileUri: gs://wlt-demo-wf/sql/2_read-data-job.sql
    scriptVariables:
      OUTPUT_PATH: gs://wlt-demo-wf
  prerequisiteStepIds:
    - "1_load-data-job"
  stepId: 2_read-data-job

placement:
  managedCluster:
    clusterName: two-node-cluster
    config:
      gceClusterConfig:
        zoneUri: us-central1-f
      masterConfig:
        diskConfig:
          bootDiskSizeGb: 250
        machineTypeUri: n1-standard-2
      softwareConfig:
        imageVersion: 1.3-deb9
      workerConfig:
        diskConfig:
          bootDiskSizeGb: 250
        machineTypeUri: n1-standard-2
        numInstances: 2